filemode;
execfile ./tests/index-create-delete-0.sql;
execfile ./tests/index-create-delete-1.sql;
execfile ./tests/index-create-delete-2.sql;
execfile ./tests/table-create-drop-0.sql;
execfile ./tests/table-create-drop-1.sql;
execfile ./tests/table-create-drop-2.sql;
execfile ./tests/table-insert-delete-0.sql;
execfile ./tests/table-insert-delete-1.sql;
execfile ./tests/table-select-0.sql;
execfile ./tests/table-select-1.sql;
execfile ./tests/test-1000.sql;
execfile ./tests/test-1w.sql;
